# Titanic Survival Rate

In [193]:
import pandas as pd
df = pd.read_csv('titanic.csv')
df.head()

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0

In [194]:
df.drop(['PassengerId', 'Name', 'SibSp', "Parch", 'Ticket', 'Cabin', 'Embarked'], axis=1, inplace=True)
df.head()

   Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [195]:
inputs = df.drop(['Survived'], axis=1)
target = df['Survived']

In [196]:
dummies = pd.get_dummies(inputs.Sex)
dummies.head()

   female   male
0   False   True
1    True  False
2    True  False
3    True  False
4   False   True

In [197]:
inputs = pd.concat([inputs, dummies], axis=1)
inputs.head()

   Pclass     Sex   Age     Fare  female   male
0       3    male  22.0   7.2500   False   True
1       1  female  38.0  71.2833    True  False
2       3  female  26.0   7.9250    True  False
3       1  female  35.0  53.1000    True  False
4       3    male  35.0   8.0500   False   True

In [198]:
inputs.drop(['Sex', 'male'], axis=1, inplace=True)
inputs.head()

   Pclass   Age     Fare  female
0       3  22.0   7.2500   False
1       1  38.0  71.2833    True
2       3  26.0   7.9250    True
3       1  35.0  53.1000    True
4       3  35.0   8.0500   False

In [199]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [200]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head()

   Pclass   Age     Fare  female
0       3  22.0   7.2500   False
1       1  38.0  71.2833    True
2       3  26.0   7.9250    True
3       1  35.0  53.1000    True
4       3  35.0   8.0500   False

In [201]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs, target, test_size=0.2)

In [202]:
len(X_train)

712

In [203]:
len(X_test)

179

In [204]:
len(inputs)

891

In [205]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [206]:
model.fit(X_train, y_train)

GaussianNB()

In [207]:
model.score(X_test, y_test)

0.7932960893854749

In [208]:
X_test[:10]

     Pclass   Age     Fare  female
645       1  48.0  76.7292   False
38        3  18.0  18.0000    True
163       3  17.0   8.6625   False
71        3  16.0  46.9000    True
153       3  40.5  14.5000   False
625       1  61.0  32.3208   False
503       3  37.0   9.5875    True
726       2  30.0  21.0000    True
283       3  19.0   8.0500   False
80        3  22.0   9.0000   False

In [209]:
y_test[:10]

645    1
38     0
163    0
71     0
153    0
625    0
503    0
726    1
283    1
80     0
Name: Survived, dtype: int64

In [210]:
model.predict(X_test[:10])

array([1, 1, 0, 1, 0, 0, 1, 1, 0, 0], dtype=int64)